spring.application.name=fuelpriceapi

spring.datasource.url=jdbc:postgresql://localhost:5432/fuelprice
spring.datasource.username=postgres
spring.datasource.password=s3inf09

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true